### ISSUE TITLE
Port from asyncio to threads

### ISSUE THREAD

**Issue by link2xt** [deltachat-bot/faqbot#2]
deltachat-rpc-client bindings have been switched from asyncio to threads here: https://github.com/deltachat/deltachat-core-rust/pull/4787

deltabot-cli dependency needs an update first: https://github.com/deltachat-bot/deltabot-cli-py/issues/1

**Comment by adbenitez** [comment]
fixed by 35987e48d0f310ef44a2cb9cd63abbf48b84106b
